name: Shellcheck

on:
    push:
        branches:
            - master

jobs:
    shellcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Shellcheck
              run: |
                sudo apt-get install shellcheck -y

            - name: Run Shellcheck
              run: shellcheck gist.sh